version: '3.3'

services:
  web:
    build: ./chatRoom
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chatRoom/:/usr/src/chatRoom/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - ./chatRoom/redis:/root/redis
